image: 
  name: kroniak/ssh-client
stages:
  - deploy
deploy-job:      
  stage: deploy  
  only:
    - master
  script:
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    - echo "$HUB_SSH_KEY" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh ubuntu@$HUB_SSH_HOST 'echo $PATH'
    - ssh ubuntu@$HUB_SSH_HOST 'bash -c "cd ~/rawscholar-bench && sudo bench update"'

