image: 
  name: ubuntu
stages:
  - deploy
deploy-job:      
  stage: deploy  
  only:
    - master
  script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$HUB_SSH_KEY")
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh ubuntu@$HUB_SSH_HOST 'source ~/.bashrc && node -v && python3 -v'
    #- ssh ubuntu@$HUB_SSH_HOST 'export NVM_DIR="$HOME/.nvm" && [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" && export PATH="$NVM_DIR/versions/node/$(nvm current)/bin:$PATH" && nvm use 20 && node --version && cd ~/rawscholar-bench && node --version && sudo bench update'


